/**
 * SnapshotManager — creates versioned snapshots of the agenttree workspace
 * before and after benchmark runs.
 *
 * Directory layout:
 *   snapshots/
 *     {benchmark}_{split}_{model}_{timestamp}/
 *       pre/                    # State before the run
 *         agents/*.md
 *         skills/** /*.md
 *         memory/*.jsonl
 *         memory.db
 *         vector_store.db
 *         manifest.json
 *       post/                   # State after the run
 *         agents/*.md
 *         skills/** /*.md
 *         memory/*.jsonl
 *         memory.db
 *         vector_store.db
 *         manifest.json
 *       results.json            # Benchmark results (copied after run)
 *       diff.json               # Automatic pre→post diff
 *
 * Usage:
 *   const mgr = new SnapshotManager(baseDir, snapshotsDir)
 *   const runId = mgr.createRunId({ benchmark, split, model })
 *   await mgr.snapshotPre(runId)     // Before benchmark
 *   // ... run benchmark ...
 *   await mgr.snapshotPost(runId)    // After benchmark
 *   await mgr.saveResults(runId, resultsObject)
 *   await mgr.generateDiff(runId)
 */

import {
  cp,
  mkdir,
  readdir,
  readFile,
  writeFile,
  stat,
} from "node:fs/promises"
import { join, relative } from "node:path"
import { createHash } from "node:crypto"
import { execSync } from "node:child_process"

export interface SnapshotRunConfig {
  benchmark: string
  split: string
  model: string
  timestamp?: string
}

export interface ManifestInfo {
  runId: string
  phase: "pre" | "post"
  timestamp: string
  gitCommit: string
  gitBranch: string
  benchmark: string
  split: string
  model: string
  agents: AgentSummary[]
  skills: SkillSummary[]
  memoryFiles: MemoryFileSummary[]
  hasMemoryDb: boolean
  hasVectorStoreDb: boolean
}

export interface AgentSummary {
  id: string
  file: string
  role: string
  version: string
  contentHash: string
  sizeBytes: number
}

export interface SkillSummary {
  id: string
  file: string
  tags: string[]
  version: string
  autoGenerated: boolean
  contentHash: string
  sizeBytes: number
}

export interface MemoryFileSummary {
  agent: string
  file: string
  entries: number
  sizeBytes: number
}

export interface DiffReport {
  runId: string
  timestamp: string
  agents: {
    added: string[]
    removed: string[]
    modified: AgentDiff[]
    unchanged: string[]
  }
  skills: {
    added: string[]
    removed: string[]
    modified: SkillDiff[]
    unchanged: string[]
  }
  memory: {
    pre: MemoryFileSummary[]
    post: MemoryFileSummary[]
    totalEntriesAdded: number
  }
  databases: {
    memoryDbSizePre: number
    memoryDbSizePost: number
    vectorStoreDbSizePre: number
    vectorStoreDbSizePost: number
  }
}

export interface AgentDiff {
  id: string
  changes: string[]
  versionPre: string
  versionPost: string
}

export interface SkillDiff {
  id: string
  changes: string[]
  versionPre: string
  versionPost: string
  sizeDelta: number
}

export class SnapshotManager {
  constructor(
    private baseDir: string,
    private snapshotsDir?: string,
  ) {
    if (!snapshotsDir) {
      this.snapshotsDir = join(baseDir, "snapshots")
    }
  }

  createRunId(config: SnapshotRunConfig): string {
    const ts =
      config.timestamp ??
      new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19)
    return `${config.benchmark}_${config.split}_${config.model.replace(/[/\\:]/g, "-")}_${ts}`
  }

  async snapshotPre(runId: string, config?: SnapshotRunConfig): Promise<string> {
    return this.snapshot(runId, "pre", config)
  }

  async snapshotPost(runId: string, config?: SnapshotRunConfig): Promise<string> {
    return this.snapshot(runId, "post", config)
  }

  private async snapshot(
    runId: string,
    phase: "pre" | "post",
    config?: SnapshotRunConfig,
  ): Promise<string> {
    const phaseDir = join(this.snapshotsDir!, runId, phase)
    await mkdir(phaseDir, { recursive: true })

    // Copy agents
    await this.copyDirIfExists(
      join(this.baseDir, "agents"),
      join(phaseDir, "agents"),
    )

    // Copy skills (recursive)
    await this.copyDirIfExists(
      join(this.baseDir, "skills"),
      join(phaseDir, "skills"),
    )

    // Copy memory JSONL files
    await this.copyDirIfExists(
      join(this.baseDir, "memory"),
      join(phaseDir, "memory"),
    )

    // Copy databases
    await this.copyFileIfExists(
      join(this.baseDir, "memory.db"),
      join(phaseDir, "memory.db"),
    )
    await this.copyFileIfExists(
      join(this.baseDir, "vector_store.db"),
      join(phaseDir, "vector_store.db"),
    )

    // Generate manifest
    const manifest = await this.generateManifest(runId, phase, phaseDir, config)
    await writeFile(
      join(phaseDir, "manifest.json"),
      JSON.stringify(manifest, null, 2),
      "utf-8",
    )

    return phaseDir
  }

  async saveResults(runId: string, results: unknown): Promise<string> {
    const runDir = join(this.snapshotsDir!, runId)
    await mkdir(runDir, { recursive: true })
    const path = join(runDir, "results.json")
    await writeFile(path, JSON.stringify(results, null, 2), "utf-8")
    return path
  }

  async copyResultsFile(runId: string, srcPath: string): Promise<void> {
    const runDir = join(this.snapshotsDir!, runId)
    await mkdir(runDir, { recursive: true })
    await cp(srcPath, join(runDir, "results.json"))
  }

  async generateDiff(runId: string): Promise<DiffReport> {
    const preManifestPath = join(
      this.snapshotsDir!,
      runId,
      "pre",
      "manifest.json",
    )
    const postManifestPath = join(
      this.snapshotsDir!,
      runId,
      "post",
      "manifest.json",
    )

    const preMani: ManifestInfo = JSON.parse(
      await readFile(preManifestPath, "utf-8"),
    )
    const postMani: ManifestInfo = JSON.parse(
      await readFile(postManifestPath, "utf-8"),
    )

    // Agent diff
    const preAgentMap = new Map(preMani.agents.map((a) => [a.id, a]))
    const postAgentMap = new Map(postMani.agents.map((a) => [a.id, a]))

    const agentAdded = postMani.agents
      .filter((a) => !preAgentMap.has(a.id))
      .map((a) => a.id)
    const agentRemoved = preMani.agents
      .filter((a) => !postAgentMap.has(a.id))
      .map((a) => a.id)
    const agentModified: AgentDiff[] = []
    const agentUnchanged: string[] = []

    for (const [id, preAgent] of preAgentMap) {
      const postAgent = postAgentMap.get(id)
      if (!postAgent) continue
      if (preAgent.contentHash !== postAgent.contentHash) {
        agentModified.push({
          id,
          changes: await this.diffFiles(
            join(this.snapshotsDir!, runId, "pre", "agents", preAgent.file),
            join(this.snapshotsDir!, runId, "post", "agents", postAgent.file),
          ),
          versionPre: preAgent.version,
          versionPost: postAgent.version,
        })
      } else {
        agentUnchanged.push(id)
      }
    }

    // Skill diff
    const preSkillMap = new Map(preMani.skills.map((s) => [s.id, s]))
    const postSkillMap = new Map(postMani.skills.map((s) => [s.id, s]))

    const skillAdded = postMani.skills
      .filter((s) => !preSkillMap.has(s.id))
      .map((s) => s.id)
    const skillRemoved = preMani.skills
      .filter((s) => !postSkillMap.has(s.id))
      .map((s) => s.id)
    const skillModified: SkillDiff[] = []
    const skillUnchanged: string[] = []

    for (const [id, preSkill] of preSkillMap) {
      const postSkill = postSkillMap.get(id)
      if (!postSkill) continue
      if (preSkill.contentHash !== postSkill.contentHash) {
        skillModified.push({
          id,
          changes: await this.diffFiles(
            join(this.snapshotsDir!, runId, "pre", "skills", preSkill.file),
            join(this.snapshotsDir!, runId, "post", "skills", postSkill.file),
          ),
          versionPre: preSkill.version,
          versionPost: postSkill.version,
          sizeDelta: postSkill.sizeBytes - preSkill.sizeBytes,
        })
      } else {
        skillUnchanged.push(id)
      }
    }

    // Memory diff
    const preMemTotal = preMani.memoryFiles.reduce((s, m) => s + m.entries, 0)
    const postMemTotal = postMani.memoryFiles.reduce((s, m) => s + m.entries, 0)

    // Database sizes
    const preMemDbSize = await this.fileSize(
      join(this.snapshotsDir!, runId, "pre", "memory.db"),
    )
    const postMemDbSize = await this.fileSize(
      join(this.snapshotsDir!, runId, "post", "memory.db"),
    )
    const preVecDbSize = await this.fileSize(
      join(this.snapshotsDir!, runId, "pre", "vector_store.db"),
    )
    const postVecDbSize = await this.fileSize(
      join(this.snapshotsDir!, runId, "post", "vector_store.db"),
    )

    const diff: DiffReport = {
      runId,
      timestamp: new Date().toISOString(),
      agents: {
        added: agentAdded,
        removed: agentRemoved,
        modified: agentModified,
        unchanged: agentUnchanged,
      },
      skills: {
        added: skillAdded,
        removed: skillRemoved,
        modified: skillModified,
        unchanged: skillUnchanged,
      },
      memory: {
        pre: preMani.memoryFiles,
        post: postMani.memoryFiles,
        totalEntriesAdded: postMemTotal - preMemTotal,
      },
      databases: {
        memoryDbSizePre: preMemDbSize,
        memoryDbSizePost: postMemDbSize,
        vectorStoreDbSizePre: preVecDbSize,
        vectorStoreDbSizePost: postVecDbSize,
      },
    }

    await writeFile(
      join(this.snapshotsDir!, runId, "diff.json"),
      JSON.stringify(diff, null, 2),
      "utf-8",
    )

    return diff
  }

  async listSnapshots(): Promise<string[]> {
    try {
      const entries = await readdir(this.snapshotsDir!, { withFileTypes: true })
      return entries.filter((e) => e.isDirectory()).map((e) => e.name).sort()
    } catch {
      return []
    }
  }

  async getManifest(runId: string, phase: "pre" | "post"): Promise<ManifestInfo> {
    const path = join(this.snapshotsDir!, runId, phase, "manifest.json")
    return JSON.parse(await readFile(path, "utf-8"))
  }

  async getDiff(runId: string): Promise<DiffReport> {
    const path = join(this.snapshotsDir!, runId, "diff.json")
    return JSON.parse(await readFile(path, "utf-8"))
  }

  // ── Internal helpers ──────────────────────────────────────────────

  private async generateManifest(
    runId: string,
    phase: "pre" | "post",
    phaseDir: string,
    config?: SnapshotRunConfig,
  ): Promise<ManifestInfo> {
    let gitCommit = "unknown"
    let gitBranch = "unknown"
    try {
      gitCommit = execSync("git rev-parse --short HEAD", {
        cwd: this.baseDir,
        encoding: "utf-8",
      }).trim()
      gitBranch = execSync("git rev-parse --abbrev-ref HEAD", {
        cwd: this.baseDir,
        encoding: "utf-8",
      }).trim()
    } catch {
      // not in a git repo
    }

    const agents = await this.scanAgents(join(phaseDir, "agents"))
    const skills = await this.scanSkills(join(phaseDir, "skills"))
    const memoryFiles = await this.scanMemory(join(phaseDir, "memory"))

    return {
      runId,
      phase,
      timestamp: new Date().toISOString(),
      gitCommit,
      gitBranch,
      benchmark: config?.benchmark ?? this.parseBenchmarkFromRunId(runId),
      split: config?.split ?? this.parseSplitFromRunId(runId),
      model: config?.model ?? this.parseModelFromRunId(runId),
      agents,
      skills,
      memoryFiles,
      hasMemoryDb: await this.fileExists(join(phaseDir, "memory.db")),
      hasVectorStoreDb: await this.fileExists(join(phaseDir, "vector_store.db")),
    }
  }

  private parseBenchmarkFromRunId(runId: string): string {
    return runId.split("_")[0] ?? "unknown"
  }

  private parseSplitFromRunId(runId: string): string {
    return runId.split("_")[1] ?? "unknown"
  }

  private parseModelFromRunId(runId: string): string {
    // runId format: benchmark_split_model_timestamp
    const parts = runId.split("_")
    // Model might contain hyphens, timestamp is the last 19 chars
    return parts.slice(2, -2).join("_") || "unknown"
  }

  private async scanAgents(dir: string): Promise<AgentSummary[]> {
    const results: AgentSummary[] = []
    let files: string[]
    try {
      files = await readdir(dir)
    } catch {
      return results
    }

    for (const file of files) {
      if (!file.endsWith(".md")) continue
      const content = await readFile(join(dir, file), "utf-8")
      const meta = this.parseYamlFrontmatter(content)
      const st = await stat(join(dir, file))

      results.push({
        id: (meta.id as string) ?? file.replace(/\.md$/, ""),
        file,
        role: (meta.role as string) ?? "unknown",
        version: (meta.version as string) ?? "0.0.0",
        contentHash: this.hash(content),
        sizeBytes: st.size,
      })
    }

    return results.sort((a, b) => a.id.localeCompare(b.id))
  }

  private async scanSkills(dir: string): Promise<SkillSummary[]> {
    const results: SkillSummary[] = []
    const files = await this.walkDir(dir)

    for (const relPath of files) {
      if (!relPath.endsWith(".md")) continue
      const fullPath = join(dir, relPath)
      const content = await readFile(fullPath, "utf-8")
      const meta = this.parseYamlFrontmatter(content)
      const st = await stat(fullPath)

      const skillId = relPath.replace(/\.md$/, "").replace(/\\/g, "/")
      results.push({
        id: skillId,
        file: relPath,
        tags: (meta.tags as string[]) ?? [],
        version: (meta.version as string) ?? "0.0.0",
        autoGenerated:
          relPath.includes("_auto") ||
          ((meta.tags as string[]) ?? []).includes("auto-generated"),
        contentHash: this.hash(content),
        sizeBytes: st.size,
      })
    }

    return results.sort((a, b) => a.id.localeCompare(b.id))
  }

  private async scanMemory(dir: string): Promise<MemoryFileSummary[]> {
    const results: MemoryFileSummary[] = []
    let files: string[]
    try {
      files = await readdir(dir)
    } catch {
      return results
    }

    for (const file of files) {
      if (!file.endsWith(".jsonl")) continue
      const fullPath = join(dir, file)
      const content = await readFile(fullPath, "utf-8")
      const lines = content.trim().split("\n").filter(Boolean)
      const st = await stat(fullPath)

      results.push({
        agent: file.replace(/\.jsonl$/, ""),
        file,
        entries: lines.length,
        sizeBytes: st.size,
      })
    }

    return results.sort((a, b) => a.agent.localeCompare(b.agent))
  }

  private parseYamlFrontmatter(content: string): Record<string, unknown> {
    const match = content.match(/^---\n([\s\S]*?)\n---/)
    if (!match) return {}
    const yaml = match[1]
    const result: Record<string, unknown> = {}
    for (const line of yaml.split("\n")) {
      const colonIdx = line.indexOf(":")
      if (colonIdx === -1) continue
      const key = line.slice(0, colonIdx).trim()
      let value: unknown = line.slice(colonIdx + 1).trim()
      if (typeof value === "string" && value.startsWith("[")) {
        try {
          value = JSON.parse(value.replace(/'/g, '"'))
        } catch {
          // leave as string
        }
      }
      result[key] = value
    }
    return result
  }

  private async diffFiles(pathA: string, pathB: string): Promise<string[]> {
    const changes: string[] = []
    try {
      const contentA = await readFile(pathA, "utf-8")
      const contentB = await readFile(pathB, "utf-8")

      const linesA = contentA.split("\n")
      const linesB = contentB.split("\n")

      if (linesA.length !== linesB.length) {
        changes.push(`Line count: ${linesA.length} → ${linesB.length}`)
      }

      const sizeA = Buffer.byteLength(contentA)
      const sizeB = Buffer.byteLength(contentB)
      if (sizeA !== sizeB) {
        changes.push(`Size: ${sizeA} → ${sizeB} bytes (${sizeB > sizeA ? "+" : ""}${sizeB - sizeA})`)
      }

      // Check YAML frontmatter changes
      const metaA = this.parseYamlFrontmatter(contentA)
      const metaB = this.parseYamlFrontmatter(contentB)
      for (const key of new Set([...Object.keys(metaA), ...Object.keys(metaB)])) {
        const valA = JSON.stringify(metaA[key])
        const valB = JSON.stringify(metaB[key])
        if (valA !== valB) {
          if (metaA[key] === undefined) {
            changes.push(`Added metadata: ${key} = ${valB}`)
          } else if (metaB[key] === undefined) {
            changes.push(`Removed metadata: ${key}`)
          } else {
            changes.push(`Changed metadata: ${key}: ${valA} → ${valB}`)
          }
        }
      }

      // Count new sections in body
      const sectionsA = contentA.match(/^##+ /gm)?.length ?? 0
      const sectionsB = contentB.match(/^##+ /gm)?.length ?? 0
      if (sectionsA !== sectionsB) {
        changes.push(`Sections: ${sectionsA} → ${sectionsB}`)
      }
    } catch (err) {
      changes.push(`Error comparing: ${err instanceof Error ? err.message : String(err)}`)
    }

    return changes
  }

  private async copyDirIfExists(src: string, dest: string): Promise<void> {
    try {
      await stat(src)
      await cp(src, dest, { recursive: true })
    } catch {
      await mkdir(dest, { recursive: true })
    }
  }

  private async copyFileIfExists(src: string, dest: string): Promise<void> {
    try {
      await stat(src)
      await cp(src, dest)
    } catch {
      // file doesn't exist, skip
    }
  }

  private async fileExists(path: string): Promise<boolean> {
    try {
      await stat(path)
      return true
    } catch {
      return false
    }
  }

  private async fileSize(path: string): Promise<number> {
    try {
      const s = await stat(path)
      return s.size
    } catch {
      return 0
    }
  }

  private hash(content: string): string {
    return createHash("md5").update(content).digest("hex")
  }

  private async walkDir(dir: string): Promise<string[]> {
    const results: string[] = []
    let entries: string[]
    try {
      entries = await readdir(dir)
    } catch {
      return results
    }

    for (const entry of entries) {
      const fullPath = join(dir, entry)
      const info = await stat(fullPath)
      if (info.isDirectory()) {
        const sub = await this.walkDir(fullPath)
        for (const s of sub) results.push(join(entry, s))
      } else {
        results.push(entry)
      }
    }

    return results
  }
}
